/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Fronted;

import Fronted.VentanaPrincipal.FondoImagen;



/**
 *
 * @author sago04
 */
public class Login extends javax.swing.JPanel {
    
    private VentanaPrincipal VentanaLogin;
    //private Image imagen;
    
    /**
     * Creates new form PanelIniciosesion
     */
    public Login(VentanaPrincipal Ventana) {
        initComponents();
        VentanaLogin=Ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelcentralSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextPasword = new javax.swing.JPasswordField();
        PanelRegreso = new javax.swing.JPanel();
        BotRegresar = new javax.swing.JButton();
        PanelAceptar = new javax.swing.JPanel();
        BotAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(new java.awt.BorderLayout());

        PanelcentralSesion.setBackground(new java.awt.Color(255, 255, 255));
        PanelcentralSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel1.setText("Usuario");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelcentralSesion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 40));

        TextUsuario.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        TextUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelcentralSesion.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        jLabel2.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        PanelcentralSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        TextPasword.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        TextPasword.setText("111");
        TextPasword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelcentralSesion.add(TextPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 170, -1));

        add(PanelcentralSesion, java.awt.BorderLayout.CENTER);

        PanelRegreso.setBackground(new java.awt.Color(51, 153, 255));
        PanelRegreso.setLayout(new javax.swing.BoxLayout(PanelRegreso, javax.swing.BoxLayout.LINE_AXIS));

        BotRegresar.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        BotRegresar.setText("Regresar");
        BotRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRegresarActionPerformed(evt);
            }
        });
        PanelRegreso.add(BotRegresar);

        add(PanelRegreso, java.awt.BorderLayout.PAGE_START);

        PanelAceptar.setBackground(new java.awt.Color(153, 204, 255));

        BotAceptar.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        BotAceptar.setText("Aceptar");
        BotAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAceptarActionPerformed(evt);
            }
        });
        PanelAceptar.add(BotAceptar);

        add(PanelAceptar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void BotAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotAceptarActionPerformed

    private void BotRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRegresarActionPerformed
        VentanaLogin.EliminarPanel(this);// TODO add your handling code here:
    }//GEN-LAST:event_BotRegresarActionPerformed
    
    /*@Override
    public void paint(Graphics g){
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Is.jpg")).getImage();
        g.drawImage(imagen, 0, 0, PanelcentralSesion.getWidth(), PanelcentralSesion.getHeight(), this);
        PanelAceptar.setOpaque(false);
        PanelcentralSesion.paint(g);
        
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAceptar;
    private javax.swing.JButton BotRegresar;
    private javax.swing.JPanel PanelAceptar;
    private javax.swing.JPanel PanelRegreso;
    private javax.swing.JPanel PanelcentralSesion;
    private javax.swing.JPasswordField TextPasword;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
